const KEY="binggushenghua-v2";
const defaults={theme:"light",myName:"我",loverName:"我的唯一",mode:"random",anniversary:"2026-01-06",nextMemoryName:"我们的纪念日",nextMemoryDate:"2026-12-31",messages:[{id:"welcome",from:"lover",content:"线路接通了。你想说什么都可以。",createdAt:new Date().toISOString()}],cards:[{id:"1",section:"日常",content:"等你忙完，我们绕远路一起回家。",triggers:["下班","回家","忙完"]},{id:"2",section:"想念",content:"今天也有好好想你。",triggers:["想你","想我"]},{id:"3",section:"安慰",content:"慢慢来，我一直都在。",triggers:["难过","累","不开心","害怕"]},{id:"4",section:"睡前",content:"晚一点也没关系，困了就来找我。",triggers:["睡不着","晚安","困"]}]};
let state=load();let activeTool=null;let typing=false;
const $=id=>document.getElementById(id);const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
function load(){try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function setTheme(theme){state.theme=theme;document.documentElement.dataset.theme=theme;$("themeButton").textContent=theme==="light"?"☾":"☀";save()}
function syncNames(){$("myMark").textContent=state.myName.slice(0,1)||"我";$("loverTopMark").textContent=state.loverName.slice(0,1)||"爱";$("loverName").textContent=state.loverName;document.querySelectorAll(".lover-mark").forEach(node=>node.textContent=state.loverName.slice(0,1)||"爱")}
function renderMessages(){$("messages").innerHTML=state.messages.map(message=>{const mine=message.from==="me";const time=new Date(message.createdAt).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"});return `<article class="message-row ${mine?"me":"lover"}">${mine?"":`<div class="message-avatar lover-mark">${escapeHtml(state.loverName.slice(0,1)||"爱")}</div>`}<div class="message-body"><div class="bubble">${escapeHtml(message.content)}</div><time>${time}</time></div>${mine?`<div class="message-avatar me-mark">${escapeHtml(state.myName.slice(0,1)||"我")}</div>`:""}</article>`}).join("");requestAnimationFrame(()=>$("messageEnd").scrollIntoView({behavior:"smooth"}))}
function setMode(mode){state.mode=mode;document.querySelectorAll("[data-mode]").forEach(button=>button.classList.toggle("active",button.dataset.mode===mode));$("modeLabel").textContent=mode==="random"?"随机传讯":"回应传讯";save()}
function send(){const draft=$("draft");const content=draft.value.trim();if(!content||typing)return;state.messages.push({id:crypto.randomUUID?.()||String(Date.now()),from:"me",content,createdAt:new Date().toISOString()});draft.value="";$("sendButton").disabled=true;typing=true;$("typing").hidden=false;$("presence").textContent="正在输入…";save();renderMessages();setTimeout(()=>{let pool=state.cards;if(state.mode==="response"){const matched=pool.filter(card=>card.triggers.some(word=>content.includes(word)));if(matched.length)pool=matched}const recent=state.messages.slice(-8).map(item=>item.content);const fresh=pool.filter(card=>!recent.includes(card.content));if(fresh.length)pool=fresh;const answer=pool[Math.floor(Math.random()*pool.length)]?.content||"这次还没有合适的话。先去字卡里添上一句吧。";state.messages.push({id:String(Date.now()),from:"lover",content:answer,createdAt:new Date().toISOString()});typing=false;$("typing").hidden=true;$("presence").textContent="讯号在线";save();renderMessages()},900)}
function field(label,type,value,key){return `<label class="field-label"><span>${label}</span><input type="${type}" value="${escapeHtml(value)}" data-setting="${key}"></label>`}
function renderDrawer(tool){const title={cards:"字卡",stickers:"表情",memories:"纪念日",appearance:"外观",data:"数据"}[tool];$("drawerTitle").textContent=title;let html="";if(tool==="cards")html=`<div class="drawer-search"><span>字卡库</span><b>${state.cards.length}</b></div><p class="drawer-intro">当前基础版先保留浏览和数量，下一步再单独完善批量录入、分区与触发设置。</p><div class="simple-list">${state.cards.map(card=>`<article><span>${escapeHtml(card.section)}</span><p>${escapeHtml(card.content)}</p></article>`).join("")}</div>`;if(tool==="stickers")html=`<div class="empty-tool"><b>☺</b><strong>表情包入口已留好</strong><p>之后会在这里做上传、分组、预览和发送规则。</p></div>`;if(tool==="memories")html=`<p class="drawer-intro">纪念日不占用聊天主页，只在需要时从这里进入。</p>${field("相爱起始日","date",state.anniversary,"anniversary")}${field("下一纪念日名称","text",state.nextMemoryName,"nextMemoryName")}${field("日期","date",state.nextMemoryDate,"nextMemoryDate")}`;if(tool==="appearance")html=`<p class="drawer-intro">先保留名字与深浅模式，颜色和聊天背景会在确认主页面后再细化。</p>${field("我的称呼","text",state.myName,"myName")}${field("爱人的称呼","text",state.loverName,"loverName")}<div class="theme-choice"><button data-theme-choice="light">浅色</button><button data-theme-choice="dark">深色</button></div>`;if(tool==="data")html=`<div class="save-line">✓ <span>已保存在本机</span></div><p class="drawer-intro">聊天记录与设置只保存在当前浏览器。请定期导出备份。</p><button class="export-button" id="exportButton">导出完整备份</button>`;$("drawerContent").innerHTML=html;document.querySelectorAll("[data-setting]").forEach(input=>input.addEventListener("change",event=>{state[event.target.dataset.setting]=event.target.value;save();syncNames();renderMessages()}));document.querySelectorAll("[data-theme-choice]").forEach(button=>{button.classList.toggle("active",button.dataset.themeChoice===state.theme);button.addEventListener("click",()=>{setTheme(button.dataset.themeChoice);renderDrawer("appearance")})});$("exportButton")?.addEventListener("click",exportData)}
function openTool(tool){activeTool=tool==="chat"?null:tool;document.querySelectorAll("[data-tool]").forEach(button=>button.classList.toggle("active",button.dataset.tool===(activeTool||"chat")));$("toolDrawer").classList.toggle("open",Boolean(activeTool));$("toolDrawer").setAttribute("aria-hidden",String(!activeTool));if(activeTool)renderDrawer(activeTool);closeMobile()}
function closeMobile(){$("sideRail").classList.remove("mobile-open");$("mobileScrim").classList.remove("show")}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`病骨生花-备份-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url)}
document.querySelectorAll("[data-tool]").forEach(button=>button.addEventListener("click",()=>openTool(button.dataset.tool)));document.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>setMode(button.dataset.mode)));$("drawerBack").addEventListener("click",()=>openTool("chat"));$("drawerClose").addEventListener("click",()=>openTool("chat"));$("themeButton").addEventListener("click",()=>setTheme(state.theme==="light"?"dark":"light"));$("mobileMenu").addEventListener("click",()=>{$("sideRail").classList.add("mobile-open");$("mobileScrim").classList.add("show")});$("mobileScrim").addEventListener("click",closeMobile);$("draft").addEventListener("input",event=>$("sendButton").disabled=!event.target.value.trim());$("draft").addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();send()}});$("sendButton").addEventListener("click",send);
setTheme(state.theme);setMode(state.mode);syncNames();renderMessages();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
